# Generated by adrienm7/ergopti tools/build/homebrew-cask.cjs on release v0.0.0-dev.156; do not edit.
cask "ergoptiplus@dev" do
  version "0.0.0-dev.156"
  sha256 "400238d1e401a1342c7d96a380eee63fc14805360df5dd78025c4552df3fc224"

  url "https://github.com/adrienm7/ergopti/releases/download/v#{version}/ErgoptiPlus.app.tar.xz"
  name "Ergopti+ (dev channel)"
  desc "Ergopti keyboard layout companion: hotstrings, tap-holds, gestures and AI"
  homepage "https://ergopti.fr/"

  livecheck do
    url "https://raw.githubusercontent.com/adrienm7/ergopti/sparkle-appcasts/appcast-dev.xml"
    strategy :sparkle, &:short_version
  end

  conflicts_with cask: "ergoptiplus"
  depends_on macos: ">= :big_sur"

  app "ErgoptiPlus.app"

  # A running app loads its Lua files from the bundle: it is quit before the
  # bundle is replaced, and relaunched after an upgrade if it was running.
  uninstall_preflight do
    running = system_command("/usr/bin/pgrep", args: ["-f", "/ErgoptiPlus.app/Contents/"],
                                               must_succeed: false).success?
    if running
      FileUtils.mkdir_p(File.dirname("#{Dir.home}/Library/Caches/com.ergoptiplus.app/brew-relaunch"))
      FileUtils.touch("#{Dir.home}/Library/Caches/com.ergoptiplus.app/brew-relaunch")
    end
  end

  uninstall quit: ["com.ergoptiplus.app.hammerspoon", "com.ergoptiplus.app"]

  # The app is not notarised: without this, Gatekeeper refuses to open it.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/ErgoptiPlus.app"]
    if File.exist?("#{Dir.home}/Library/Caches/com.ergoptiplus.app/brew-relaunch")
      FileUtils.rm_f("#{Dir.home}/Library/Caches/com.ergoptiplus.app/brew-relaunch")
      system_command "/usr/bin/open", args: ["#{appdir}/ErgoptiPlus.app"]
    end
  end

  zap trash: [
    "~/.config/ergopti_plus",
    "~/Library/Caches/com.ergoptiplus.app",
    "~/Library/HTTPStorages/com.ergoptiplus.app",
    "~/Library/Preferences/com.ergoptiplus.app.plist",
  ]
end
